### ISSUE TITLE
Error during process attaching

### ISSUE THREAD

**Issue by davidebeatrici** [korcankaraokcu/PINCE#13]
OS: Debian 8 x64
Desktop environment: KDE 4
```
Traceback (most recent call last):
  File "PINCE.py", line 571, in pushbutton_open_onclick
    code_injection_status = GDB_Engine.attach(str(pid), initial_code_injection_method)
  File "/usr/share/PINCE/GDB_Engine.py", line 213, in attach
    SysUtils.create_PINCE_IPC_PATH(pid)
  File "/usr/share/PINCE/SysUtils.py", line 242, in create_PINCE_IPC_PATH
    is_path_valid(get_PINCE_IPC_directory(pid), "create")
  File "/usr/share/PINCE/SysUtils.py", line 208, in is_path_valid
    fix_path_permissions(dest_path)
  File "/usr/share/PINCE/SysUtils.py", line 221, in fix_path_permissions
    uid = int(os.environ.get('SUDO_UID'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by korcankaraokcu** [comment]
This problem occurs when PINCE gets run with gksu. It may look retarded but running `gksu sudo python3 PINCE.py` solves the issue for me, or you may try kdesudo instead, it works fine too. Did running `gksu sudo python3 PINCE.py` solve the issue for you as well?

Also, it looks like there are shittons of problems with debian other than this problem. I'll investigate this further when I have got time.

**Comment by davidebeatrici** [comment]
It solves the issue, but there is another one:
```
&"source /tmp/PINCE-connection/2016/gdb_command.txt\n"
&"/tmp/PINCE-connection/2016/gdb_command.txt:1: Error in sourced command file:\n"
&"Undefined command: \"pince-read-multiple-addresses\".  Try \"help\".\n"
^error,msg="/tmp/PINCE-connection/2016/gdb_command.txt:1: Error in sourced command file:\nUndefined command: \"pince-read-multiple-addresses\".  Try \"help\"."

Traceback (most recent call last):
  File "PINCE.py", line 324, in update_address_table_manually
    new_table_contents = GDB_Engine.read_multiple_addresses(table_contents)
  File "/usr/share/PINCE/GDB_Engine.py", line 482, in read_multiple_addresses
    recv_with_file=True)
  File "/usr/share/PINCE/GDB_Engine.py", line 124, in send_command
    output = pickle.load(open(recv_file, "rb"))
EOFError: Ran out of input
```
Content of /tmp/PINCE-connection/2016/gdb_command.txt:

`
pince-read-multiple-addresses
`

**Comment by korcankaraokcu** [comment]
I just encountered the error above while testing. It happens because there's an import error in GDBCommandExtensions.py, which denies the use of custom gdb commands.

Btw, I realized that you could just use `gksudo` instead of `gksu sudo`. So it's just `gksudo python3 PINCE.py` now

**Comment by korcankaraokcu** [comment]
The solution to import error is this:

1-)Locate the psutils package by running `pip3 show psutil`
2-)import psutil explicitly in SysUtils

So, I should write a bash script I guess... Do you have a better idea other than using regex to extract location information from output? I used regex so much in the project that I'm sick of it, there should be a more elegant solution to this problem.

**Comment by davidebeatrici** [comment]
Sadly I don't.
This means that you have to import the package including the path to it?

**Comment by korcankaraokcu** [comment]
I finally found the real reason of the error above. I appended `print(sys.path)` to SysUtils and saw that GDB imports only python 2.7 related libraries. So in debian 8, if you install gdb within default package, it gets installed with python2 support, not python3. So, there's no option other than to compile GDB from source with python3 support. I'll update this as soon as I compile it successfully.

**Comment by davidebeatrici** [comment]
It's really strange the fact that Debian doesn't have a GDB package with Python 3 support.

**Comment by korcankaraokcu** [comment]
Yeah. Btw, you don't actually have to compile gdb with gcc-6, gdb needs `libcc1.so` from gcc-6 to make compile command work. But PINCE doesn't use the compile command yet. So, you may want to compile gdb with default gcc version instead of gcc-6. I'm saying this because I've completely ruined my virtual machine while trying to install gcc and gdb from testing repos :smile: Time to stop trying to avoid compiling, compiling is the safest way to achieve functionality.

**Comment by davidebeatrici** [comment]
Today I read on [StackOverflow](http://stackoverflow.com/questions/26243956/how-to-change-the-python-interpreter-that-gdb-uses) of a user that ruined Ubuntu in the same way you did... touching libc is dangerous, never mess with it! 
I nearly ruined my virtual machine too one day, because I added the Ubuntu repository to sources.list to download a package that was not available on Debian; wonder what happened when I runned `apt-get upgrade` :laughing:
Luckily I fixed libc by taking the broken files from another Debian system, you could try to do the same :wink:

**Comment by korcankaraokcu** [comment]
I finally successfully compiled gdb&installed PINCE on debian. Updated the instructions, just follow them. PINCE no longer requires gcc-6, as I've explained before, there's no need for the compile command yet. I'll think of something when compile command is needed, there should be another solution to getting the `libcc1.so` other than installing/compiling the entire gcc-6

**Comment by korcankaraokcu** [comment]
I still can't believe that all of the problems are gone after a clean compiling&installation season :smile:.  With [this commit](https://github.com/korcankaraokcu/PINCE/commit/805a26a3927b8a61187ee87c26618ac4b633677a) PINCE now supports Debian 8.5

**Comment by davidebeatrici** [comment]
I can confirm, everything works fine now :smile:

**Comment by korcankaraokcu** [comment]
Then closing this issue for once and all
